name: firebase_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1
  flutter: 3.32.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.6.0
  very_good_analysis: ^9.0.0
  firebase_core: ^3.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
